version: '3.9'

services:

#  db:
#    image: postgres:13
#    container_name: db
#    environment:
#      - POSTGRES_DB=afriluck-v2
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    ports:
#      - "5431:5432"
#    networks:
#      - app-network
#    volumes:
#      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - pgdata:/var/lib/postgresql/data
#    deploy:
#      update_config:
#        parallelism: 1
#        delay: 10s
#      resources:
#        limits:
#          cpus: '3'
#          memory: 5g
#        reservations:
#          memory: 3g
#    restart: unless-stopped
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=afriluck-v2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: >
      postgres
        -c shared_buffers=2GB
        -c work_mem=64MB
        -c maintenance_work_mem=256MB
        -c effective_cache_size=4GB
        -c wal_buffers=16MB
        -c min_wal_size=512MB
        -c max_wal_size=1GB
        -c random_page_cost=1.0
        -c checkpoint_timeout=15min
        -c max_connections=200
        -c log_min_duration_statement=500
        -c log_statement=none
        -c synchronous_commit=off
    ports:
      - "5431:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '3'
          memory: 5g
#        reservations:
#          memory: 3g
    restart: unless-stopped

  app:
    image: stevesmart1113/afriluck:latest
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8000"
    environment:
      #      - POSTGRES_USER=postgres
      #      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/afriluck-v2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #- JAVA_OPTS=-Xms2g -Xmx2g
      - JAVA_OPTS=-Xms2g -Xmx2g
    #depends_on:
    #  - db
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: '2.0'
#          memory: 5G
#        reservations:
#          cpus: '0.5'
#          memory: 2G
    networks:
      - app-network

  app1:
    image: stevesmart1113/afriluck:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8002:8000"
    environment:
      #      - POSTGRES_USER=postgres
      #      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/afriluck-v2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #- JAVA_OPTS=-Xms2g -Xmx2g
      - JAVA_OPTS=-Xms2g -Xmx2g
    #depends_on:
    #  - db
#    deploy:
#      replicas: 1

#      resources:
#        limits:
#          cpus: '2.0'
#          memory: 5G
#        reservations:
#          cpus: '0.5'
#          memory: 2G
    networks:
      - app-network


  app2:
    image: stevesmart1113/afriluck:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8003:8000"
    environment:
      #      - POSTGRES_USER=postgres
      #      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/afriluck-v2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      #- JAVA_OPTS=-Xms2g -Xmx2g
      - JAVA_OPTS=-Xms2g -Xmx2g
    #depends_on:
    #  - db
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: '2.0'
#          memory: 5G
#        reservations:
#          cpus: '0.5'
#          memory: 2G
    networks:
      - app-network

  nginx-load-balancer:
    build: nginx
    image: nginx-load-balancer:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - app
      - app1
      - app2
    links:
      - app
      - app1
      - app2

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local