version: '3.8'

services:
  app:
    image: stevesmart1113/afriluck:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/afriluck-v2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=afriluck-v2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5431:5431"