version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: afriluck-pg
    restart: always
    environment:
      POSTGRES_DB: afriluck-v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local