version: '3.8'

services:
  app:
    image: stevesmart1113/afriluck:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://5.75.226.153:5431/afriluck-v2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    #depends_on:
    #  - db
    networks:
      - app-network

  app1:
    image: stevesmart1113/afriluck:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://188.245.201.96:5431/afriluck-v2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    #depends_on:
    #  - db
    networks:
      - app-network


  app2:
    image: stevesmart1113/afriluck:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8003:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://188.245.201.96:5431/afriluck-v2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    #depends_on:
    #  - db
    networks:
      - app-network

  nginx-load-balancer:
    build: nginx
    image: nginx-load-balancer:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - app
      - app1
      - app2
    links:
      - app
      - app1
      - app2

#  db:
#    image: postgres:13
#    container_name: db
#    environment:
#      - POSTGRES_DB=afriluck-v2
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    ports:
#      - "5431:5432"
#    networks:
#      - app-network
#    volumes:
#      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - pgdata:/var/lib/postgresql/data
#    deploy:
#      update_config:
#        parallelism: 1
#        delay: 10s
#    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local